// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as Css from "bs-css/lib/es6/src/Css.js";
import * as React from "react";

var button = Css.style(/* :: */[
      Css.padding(Css.px(6)),
      /* :: */[
        Css.margin(Css.px(6)),
        /* :: */[
          Css.fontSize(Css.rem(1.0)),
          /* :: */[
            Css.borderRadius(Css.px(5)),
            /* :: */[
              Css.boxShadow(undefined, Css.px(1), Css.px(5), undefined, undefined, Css.rgba(0, 0, 0, 0.2)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var primary = Css.style(/* :: */[
      Css.color(Css.white),
      /* :: */[
        Css.backgroundColor(Css.rgb(32, 148, 243)),
        /* [] */0
      ]
    ]);

var secondary = Css.style(/* :: */[
      Css.color(Css.black),
      /* :: */[
        Css.backgroundColor(Css.rgb(224, 224, 224)),
        /* [] */0
      ]
    ]);

var disabled = Css.style(/* :: */[
      Css.color(Css.rgba(0, 0, 0, 0.26)),
      /* :: */[
        Css.backgroundColor(Css.rgba(0, 0, 0, 0.12)),
        /* [] */0
      ]
    ]);

var Styles = /* module */[
  /* button */button,
  /* primary */primary,
  /* secondary */secondary,
  /* disabled */disabled
];

function classNameOfCategory(category) {
  var buttonCategory = category ? primary : secondary;
  return Css.merge(/* :: */[
              button,
              /* :: */[
                buttonCategory,
                /* [] */0
              ]
            ]);
}

function Button(Props) {
  var onClick = Props.onClick;
  var title = Props.title;
  var children = Props.children;
  var match = Props.category;
  var category = match !== undefined ? match : /* SECONDARY */0;
  Props.type_;
  return React.createElement("button", {
              className: classNameOfCategory(category),
              title: title,
              onClick: onClick
            }, children);
}

var make = Button;

export {
  Styles ,
  classNameOfCategory ,
  make ,
  
}
/* button Not a pure module */
