// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE

import * as React from "react";

function Timer(Props) {
  return React.createElement("div", undefined, "What year is this?");
}

var make = Timer;

export {
  make ,
  
}
/* react Not a pure module */
